import { Inter } from 'next/font/google';

import type { Metadata } from "next";
import "./globals.css";
import Nav from '@/components/navigation/nav';
import Footer from '@/components/footer/footer';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <body>
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    );
}
