import { Inter } from 'next/font/google';

import type { Metadata } from "next";
import "./globals.css";
import Nav from '@/components/navigation/nav';
import Footer from '@/components/footer/footer';
import { cn } from '@/lib/utils'

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Nav />
                <div className="px-6 md:px-12 max-w-7xl mx-auto">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
